INSERT INTO CLIENTE (CREATED_AT, UPDATED_AT, NOME, EMAIL, CPF, NATURALIDADE, NACIONALIDADE, DATA_NASCIMENTO, SEXO)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'MOCK DA SILVA' , 'mock_dsilva@gmail.com', '01999759060' , 'PARAENSE', 'BRASILEIRO', '1991-11-07', 'MASCULINO');
